global:
scrape_interval: 15s


rule_files:
- "/etc/prometheus/alert_rules.yml"


scrape_configs:
- job_name: 'node-exporter'
static_configs:
- targets: ['node-exporter:9100']


# Prometheus will pick up the textfile metrics through Node Exporter; no extra file_sd needed here.
